SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Fence and Wall",
    help: "Help",
    Text1: "Method",
    Text_FollowLine: "Follow<br> Line",
    Text_CreatePolygon: "Create<br> Polygon",
    Text_SelectedGroup: "Selected<br> Group",
    Text_ObjectType: "Object Type",
    Text_Fence: "Mesh Fence",
    Text_Wall: "Wall",
	Text_WallWithFence: "Wall With Fence Top",
	Text_WireStrandFence: "Wire Strand Fence",
	Text_FenceHeight: "Top Fence Height",
	Text_FenceTexture: "Top Fence Texture",
    Text_Scale: "Scale",
	Text_FillStyle: "Fill Style",
    Text_Texture: "Texture",
	Text_Color: "Color",
    Text_Browse: "Browse",
    Text_Select: "Select",
	Text_PostStyle: "Post Type",
    Text_Sampling: "Sampling",
	Text_SimplifyLine: "Minimize line points",
	Text_Flatten: "Flat wall tops (experimental)",
	Text_PostFill: "Post Fill Style",
	Text_PostSpacing: "Post Spacing",
	Text_PostExtension: "Post Extension",
	Text_PostDiameterStyle: "Post Diameter",
    Text_WallWidth: "Wall Width",
    Text_WallHeight: "Height",
    Text_Height: "Height",
    Text_Meters: "meters",
	Text_Meters_Above_FenceTop: "meters above fence top",
	Text_Meters_Above_WallTop: "meters above wall top",
    Text_VisibilityDistance: "Visibility Distance",
    Text_CreateAs: "Create as",
    Text_Group: "Group",
    Text_Layer: "Layer (Entire)",
    Text_LayerStreaming: "Layer (Streaming)",
	Text_NumStrands: "# of Strands",
	Text_StrandColor: "Strand Color",
    Text_NewPolygon: "New polygon",
    Text_NewPolyline: "New polyline",
    Text_Browse: "Browse",
    Text_EditMessage: "Fence and wall: Left click on the terrain to set point for a line or a polygon. Right click to finish operation.",
    ERROR_TEXT_ParemetersValidationFailed: "Parameters validation has failed.",
    ERROR_TEXT_NoTexture: "No texture file selected - select a fence or wall through advanced tab",
	ERROR_TEXT_NoPostTexture: "No post texture file selected",
    ERROR_TEXT_SamplingValidation: "Sampling validation failed.",
	ERROR_TEXT_PostSpacingValidation: "Post Spacing validation failed.",
	ERROR_TEXT_PostExtensionValidation: "Post Extension validation failed.",
	ERROR_TEXT_PostDiameterValidation: "Post Diameter validation failed.",
	ERROR_TEXT_OpacityValidation: "Opacity validation failed.",
	ERROR_TEXT_FenceHeightValidation: "Fence height validation failed.",
    ERROR_TEXT_WallWidthValidation: "Wall width validation failed.",
	ERROR_TEXT_WireStrandHeightValidation: "Wire strand height validation failed.",
    ERROR_TEXT_WallHeightValidation: "Wall height validation failed.",
    ERROR_TEXT_VisibilityDistanceValidation: "Visibility distance validation failed.",
	ERROR_TEXT_TooFewStrands: "Number of strands validation failed",
    ERROR_TEXT_NoItemSelected: "No item selected",
    ERROR_TEXT_SelectedNotAGroupOrLayer: "Selected item is not a group nor a layer.",
	ERROR_TEXT_SelectedNotFeatureLayer_NoAttributes: "Selected item is not a feature layer and therefore has no attributes.",
	ERROR_TEXT_WaypointsPassedQuota: "One or more of the objects you are creating has more than 2000 points, requiring a lengthy processing time. Click OK to continue or Cancel to abort.",
	ERROR_TEXT_SamplingFenceAndPosts: "Sampling validation failed. Fence sampling interval cannot be greater than Posts sampling interval . Please insert new values.",
    Text26: "Select image",
    Text27: "Draw area",
    Text28: "Finish",
    Text_FenceAndWall: "Fence and Wall",
    Text34: "Creation completed!",
    Text37: "Adding Object ",
    Text38: "Text Label",
    Text39: "From <br>Clipboard",
    Text31: "Processing...",

    Text99: "",
	Select_A_File: "<select a file...>",
	Settings_General: "General Settings",
	Settings_FencePosts: "Fence Post Settings",
	Settings_WallPosts: "Wall Post Settings",
	Settings_Wall: "Wall Settings",
	Settings_Fence: "Fence Settings",
	Settings_Wire: "Wire Strand Settings"
 });