SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe Pro - Skyline Software Systems, Inc.",
    ToolName: "Urban Design",
    help: "Help",
    Text1: "Delete drawing elements",
    Text2: "Add Marker",
    Text3: "Draw",
    Text4: "Add Line",
    Text5: "Add Polygon",
    Text6: "Add arrow",
    Text7: "Mil-Std-2525b symbol",
    Text8: "Virtual Cursor",
    Text9: "Build road",
    Text10: "Junction",
    Text11: "Traffic Light",
    Text12: "Drawing sheets",
    Text13: "Delete",
    Text14: "Rename",
    Text15: "[Urban Design]",
    Text16: "Default sheet",
    Text17: "Cannot edit object created by SkylineGlobe Pro",
    Text18: "Error: Cannot edit object",
    Text19: "Properties",
    Text20: "Left Click on drawing elements to delete.",
    Text21: "Click and hold the mouse button to display the Virtual Cursor.",
    Text22: "Are you sure you want to delete this layer?",
    Text23: "Are you sure you want to delete this object?",
    Text24: "Cursor",
    Text25: "Help Text",
    Text26: "Are you sure you want to delete this Drawing Sheet?",

    Text27: "Name:",
    Text28: "Color: ",
    Text29: "BG: ",
    Text30: "Line Style:",
    Text31: "Line",
    Text32: "Spline",
    Text33: "Width Style: ",
    Text34: "FG: ",
    Text35: "Thin Line",
    Text36: "Thick line",
    Text37: "Line Width:",
    Text38: "meter",
    Text39: "Arrow Style: ",
    Text40: "Text: ",
    Text41: "Icon: ",
    Text42: "Select",
    Text43: "Scale: ",
    Text44: "-- Auto Scale --",
    Text45: "Street Level",
    Text46: "City Level",
    Text47: "State Level",
    Text48: "Country Level",
    Text49: "Frame: ",
    Text50: "Yes",
    Text51: "No",
    Text52: "Model: ",
    Text53: "Select",
    Text54: "Scale: ",
    Text55: "Direction:",
    Text56: "Deg.",
    Text57: "File: ",
    Text58: "X: ",
    Text59: "Longitude",
    Text60: "Latitude",
    Text61: "meter",
    Text62: "Y: ",
    Text63: "Degrees",
    Text64: "Width: ",
    Text65: "Height: ",
    Text66: "Direction: ",
    Text67: "Opacity: ",
    Text68: "Message:",
    Text69: "Text:",
    Text70: "URL: ",
    Text71: "Close",
    Text72: "Drawing Properties",
    Text73: "Drawing",
    Text74: "Line Properties",
    Text75: "Line",
    Text76: "Marker Properties",
    Text77: "Note",
    Text78: "Arrow Properties",
    Text79: "Arrow",
    Text80: "3D Model Properties",
    Text81: "3D Model",
    Text82: "Image Overlay Properties",
    Text83: "Image Overlay",
    Text84: "Polygon Properties",
    Text85: "Polygon",
    Text86: "Click and Hold the left mouse button on the terrain to draw a line. Release left button and click again to draw new lines. Right click to finish operation.",
    Text87: "Click on the terrain to place the marker. Right click to finish operation.",
    Text88: "Click left mouse button on the terrain to add point. Right click to finish line drawing.",
    Text89: "First Click on the terrain to set the arrow head. Second click to set the arrow tail.",
    Text90: "Click on the terrain to add selected model.",
    Text91: "Click on the terrain to add Image overlay.",
    Text92: "Left Click on drawing elements to delete.",
    Text93: "Click left mouse button on the terrain to add points to the polygon. Right click to finish line drawing.",
    Text94: "Select",
    Text95: "Message",
    Text96: "Roads",
    Text97: "Road Style:",
    Text98: "Road Width:",
    Text99: "meters",
    Text100: "NONE",
    Text101: "1 Lane",
    Text102: "1 Lane white ",
    Text103: "1 Lane yellow ",
    Text104: "2 Lanes",
    Text105: "2 Lanes white style A",
    Text106: "2 Lanes white style B",
    Text107: "2 Lanes white style C",
    Text108: "2 Lanes white style D",
    Text109: "2 Lanes yellow ",
    Text110: "3 Lanes",
    Text111: "3 Lanes white ",
    Text112: "3 Lanes yellow ",
    Text113: "Tiles type 1",
    Text114: "Tiles type 2",
    Text115: "Tiles type 3",
    Text116: "Tree Type:",
    Text117: "Style A",
    Text118: "Style B",
    Text119: "Style C",
    Text120: "Style D",
    Text121: "Style E",
    Text122: "Style F",
    Text123: "Random",
    Text124: "Position:",
    Text125: "Both sides",
    Text126: "Right side",
    Text127: "Left side",
    Text128: "Center",
    Text129: "Spacing:",
    Text130: "meters",
    Text131: "Distance from road:",
    Text132: "Pole Type:",
    Text133: "Position:",
    Text134: "Spacing:",
    Text135: "Junctions",
    Text136: "Style:",

    Text140: "4 roads",
    Text141: "4 roads White",
    Text142: "4 roads Yellow ",
    Text143: "3 roads",
    Text144: "3 roads White ",
    Text145: "3 roads Yellow ",
    Text146: "4 roads 2 Lanes",
    Text147: "4 roads 2 Lanes White",
    Text148: "4 roads 2 Lanes Yellow",
    Text149: "3 roads 2 Lanes ",
    Text150: "3 roads 2 Lanes White",
    Text151: "3 roads 2 Lanes Yellow",
    Text137: "Traffic Lights",
    Text138: "Traffic Light:",
    Text140: "Style A",
    Text141: "Style B",
    Text142: "Style C",
    Text143: "Style D",
    Text144: "Style E",
    Text145: "Style F",
    Text146: "Style G",
    Text147: "Style H",
    Text148: "Style I",
    Text149: "Road",
    Text150: "Warning: Couldn't find any selected polyline.\n Please select polylines and/or groups from the Information Window and click again on the Selected Polylines button",
    Text152: "RoadSegment",
    Text153: "Junction",
    Text154: "Traffic Light",
    Text162: "Style J",
    Text163: "Style K",
    Text164: "Style L",
    Text165: "Edit",
    Text166: "Left Click on drawing elements to edit.",
    notinuse: ""
});