SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName:   "Block Width",
    help: "Help",
    Text1: "Layer type",
    Text2: "Select layer type, position the camera at the layer's planned maximum altitude and click on the <b>calculate</b> button.",
    Text3: "Calculate",
    Text4: "OR",
    Text5: "Manually select the <b>Block Width</b> and view it on the terrain",
    Text6: "Number of MPT levels > 22",
    Text7: "Km",
    Text8: "m",
    Text9: "Km (Globe Level)",
    Text10: "Km (Continent Level)",
    Text11: "Km (Continent Level - Dense Layer)",
    Text12: "Km (Country Level)",
    Text13: "Km (Country Level - Dense Layer)",
    Text14: "m (State Level)",
    Text15: "m (State Level - Dense Layer)",
    Text16: "m (City Level)",
    Text17: "m (City Level - Dense Layer)",
    Text18: "m (House Level)",
    Text19: "m (House Level - Dense)",
    Text20: "Please position the camera so that its center point is lower then the horizon",
    Text21: "Please select layer type",
    Text22: "Block",
    Text23: "Suggested width: "

 });