SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Particle Editor",
    help: "Help",
    Text1: "Image",
    Text2: "Emitter Shape",
    Text3: "Cone",
    Text4: "Sphere",
    Text5: "ShellCone",
    Text6: "ShellSphere",
    Text7: "Ring",
    Text8: "Disc",
    Text9: "Cube",
    Text10: "Color",
    Text11: "Create",
    Text12: "End Edit",
    Text13: "Speed Factor",
    Text14: "Gravity",
    Text15: "Max Particles",
    Text16: "Rate (sec)",
    Text17: "Lifetime (sec)",
    Text18: "Drag",
    Text19: "Particle Size",
    Text20: "Fade",
    Text21: "In:",
    Text22: "Out:",
    Text23: "Opacity:",
    Text24: "sec",
    Text25: "%",
    Text26: "Num Emmiters",
    Text27: "Speed Direction",
    Text28: "X",
    Text29: "Y",
    Text30: "Z",
    Text31: "One",
    Text32: "Emitter Scale",
    Text33: "Blend mode",
    Text34: "Edit Selected",
    Text35: "For security reasons, the Particle Editor tool must be run from local disc (e.g. C:\) to allow selecting custom files.",
    Text36: "Selected object is not a particle.",
    Text37: "Browse...",
    Text38: "URL...",
    Text39: "No object selected",
    Text40: "Force (Wind)",
    Text41: "Wind force",
    Text42: "Affect rotation",
    Text43: "Size Ratio <br>(X/Y)",
    Text44: "Rotation",
    Text45: "Speed",
    Text46: "Time",
    Text47: "Random <br>start angle",
    Text48: "Speed Direction Shape",
    Text49: "Render",
    Text50: "Billboard",
    Text51: "Vertical",
    Text52: "Horizontal",

    Text99: "Finish"
});
