SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Build Power Lines",
    ToolName1: "Power Line",
    help: "Help",
    Text1: "Method",
    Text2: "Fix distance between poles",
    Text3: "Pole every waypoint",
    Text4: "Pole Type",
    Text5: "Pole type A",
    Text6: "Pole type B",
    Text7: "Pole type C",
    Text8: "Distance",
    Text9: "Segments in section ",
    Text10: "Maximum Line Depth",
    Text11: "Line Color",
    Text12: "Follow<br> Line",
    Text13: "Power Line",
    Text14: "Selected<br> Group",
    Text15: "Finish",
    Text16: "Build Line: Left click on the terrain to place poles. Right click or Finish button to finish operation.",
    Text17: "Line",
    Text18: "Power Line",
    Text19: "Creating Objects ...",
    Text20: "Create Power Line tool is about to create more than 2000 objects. This procedure may take some time. Do you wish to Continue?",
    Text21: "N/A",
    Text22: "Creating line ",
    Text23: "meters",
    Text24: "Please select a Group or a Layer from the project tree",
    Text25: "Create Power Lines is going to create up to ",
    Text26: " power poles. This procedure might take some time. Do you wish to Continue?",
    Text27: "Pole",
    Text28: "Pole type D",
    Text29: "Pole type E",
    Text30: "Pole type F",
    Text31: "Creating powerline ",
    Text32: "Visibility Distance",
    Text70: "Create as",
    Text71: "Group",
    Text72: "Layer (Entire)",
    Text73: "Layer (Streaming)",
    Text74: "From<br>Clipboard",

    Text999: ""
});