SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName:   "Duplicate Objects",
    help: "Help",
    Text1: "Method",
    Text2: "Follow<br> Line",
    Text3: "Fill<br> Area",
    Text3a: "Selected<br> Group",
    Text4: "Object Type",
    Text5: "Text Label",
    Text6: "Image Label",
    Text7: "Regular Polygon",
    Text8: "Arrow",
    Text9: "Circle",
    Text10: "Ellipse",
    Text11: "3D Model",
    Text12: "Box",
    Text13: "Cylinder",
    Text14: "Sphere",
    Text15: "Cone",
    Text16: "Pyramid",
    Text17: "3D Arrow",
    Text18: "Scale",
    Text19: "Text",
    Text20: "Browse",
    Text21: "Select",
    Text22: "Spacing",
    Text23: "Max Random Offset ",
    Text24: "meters",
    Text25: "Error while trying to register DuplicateObjects.",
    Text26: "Select image",
    Text27: "Draw area",
    Text28: "Finish",
    Text29: "Duplicate Objects: Left click on the terrain to set Line or Area waypoint. Right click to finish operation.",
    Text30: "Duplicate Objects",
    Text31: "Duplicating Object",
    Text32: "Duplicate Objects is going to create up to ",
    Text33: " objects. This procedure might take some time. Do you wish to Continue?",
    Text34: "Duplication completed!",
    Text35: "Polygon",
    Text36: "Polyline",
    Text37: "Adding Object ",
    Text38: "Text Label",
    Text39: "File Name field is empty. Please choose a valid Image file",
    Text40: "Image Label",
    Text41: "Illegal File Name. Please choose a valid Image file",
    Text42: "Regular Polygon",
    Text43: "Arrow",
    Text44: "Circle",
    Text45: "Ellipse",
    Text46: "File Name field is empty. Please choose a valid 3D model file",
    Text47: "Illegal File Name. Please choose a valid 3D model file",
    Text48: "Box",
    Text49: "Cylinder",
    Text50: "Sphere",
    Text51: "Cone",
    Text52: "Pyramid",
    Text53: "3D Arrow",
    Text54: "3D Model",
    Text55: "File Name",
    Text56: "Segments",
    Text57: "Radius",
    Text58: "Lenght",
    Text59: "Second Raduis",
    Text60: " meters",
    Text61: "N/A",
    Text62: "Box Height",
    Text63: "Base Size",
    Text64: "Cylinder Height",
    Text65: "Cone Height",
    Text66: "Pyramid Height",
    Text67: "Arrow Height",
    Text68: "Visibility Distance",
    Text69: "Please select a Group or a Layer from the project tree",
    Text70: "Create as",
    Text71: "Group",
    Text72: "Layer (Entire)",
    Text73: "Layer (Streaming)",
    Text74: "From<br>Clipboard",

    Text999: ""
 });