SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Slope Cursor ",
    ToolName1: "Slope Cursor",
    help: "Help",
    Text3: "Start <br/>Cursor",
    Text4: "Stop",
    Text5: "Slope Cursor Information",
    Text6: "Coords:",
    Text7: "Maximum positive slope",
    Text8: "Maximum positive slope heading",
    Text9: "Maximum negative slope",
    Text10: "Maximum negative slope heading",
    Text11: "Measure Distance",
    Text12: "Alert slope",
    Text13: "Danger slope",
    Text14: "Show heading arrow",
    Text15: "Unexpected error in Slope Query tool",
    Text16: "m",
    Text17: "deg",
    Text18: "Display Max slope values",
    Text19: "Never",
    Text20: "On click",
    Text21: "Always",
    Text22: "Display heading slope",
    Text23: "Display coordinate info",
    Text24: "",
    Text25: "",

    Text99: "Finish"
});