SGLang.lang = $.extend(SGLang.lang,{
	ToolTitle: "SkylineGlobe Pro - Skyline Software Systems, Inc.",
	ToolName: "Collaboration",
	help: "Help",
	Text1: "You are <font color=red>Not Connected</font> to a Collaboration Session.",
	Text2: "You may ",
	Text3: "Open Session",
	Text4: " Or",
	Text5: "Join Session",
	Text6: "You are <font color=green>Connected</font> to a Session. ",
	Text7: "Disconnect",
	Text8: "Session leader: ",
	Text9: "Follow leader",
	Text10: "Chat: ",
	Text11: "Send",
	Text12: "Show",
	Text13: "On user connection: ",
	Text14: "Don't Send Fly",
	Text15: "Send Fly Link",
	Text16: "Send Fly File",
	Text17: "Participants: ",
	Text18: "Set as Leader",
	Text19: "Enter Email(s): ",
	Text20: "Invite",
	Text21: "Text Label: ",
	Text22: "Connection type:",
	Text23: "Create local session",
	Text24: "Create session on server",
	Text25: "Server host name: ",
	Text26: "Enter name or IP address",
	Text27: "Choose session name: ",
	Text28: "Skyline",
	Text29: "Choose a user name: ",
	Text30: "Enter User Name",
	Text31: "Connect",
	Text32: "Please enter session name",
	Text33: "License Manager Error:",
	Text34: ". Please run Start>Programs>Skyline>License Manager for additional information",
	Text35: "TECollaboration is nothing",
	Text36: "Comm is nothing",
	Text37: "Collaboration",
	Text38: "Can't create local session.",
	Text39: "Reason: Local session already created",
	Text40: "Resolution: Close all instances of the Collaboration tool, stop the TG Collaboration Server and reconnect.",
	Text41: "The session manager has left the session.",
	Text42: "Functionality will be limited.",
	Text43: "Your nick name is already in use.",
	Text44: "Please connect again with a different nick name",
	Text45: "Synchronize Flight: OFF",
	Text46: "Synchronize Flight: ON",
	Text47: "Operation Cancelled",
	Text48: "Use the Tools panel to cancel 'Follow the leader' mode",
	Text49: "Place the text label on the terrain",
	Text50: "Click and Hold the left mouse button on the terrain to draw a line. Release left button and click again in a new location to draw a new line. Right click or Finish button to finish operation.",
	Text51: "Left click and hold to display the Virtual Cursor. Right click or Finish button to finish operation.",
	Text52: "Only the manager can set leaders",
	Text53: "The manager has reloaded a FLY file",
	Text54: "Do you wish to reconnect and get the latest file?",
	Text55: "Collaboration",
	Text56: "Connection Error: ",
	Text58: "Server Disconnected",
	Text59: "To send a Fly file/link, please open a Fly file first",
	Text60: "'Send Fly link' may not operate.\r\nReason: The current Fly file is on your local C: drive.\r\nOther users will look for the file on their local C drive.\r\nOptional resolution: Select 'Send Fly file'.",
	Text64: "'Send Fly file' not available.\r\nOn user connection is reset to 'Don't Send fly'\r\nReason: Can't transfer MPT file\r\nResolution: Please load a FLY file.",
	Text68: "When a user connects to your session, no FLY file is sent over",
	Text69: "Do you want to send a FLY link?",
	Text70: "'Send Fly link' may not operate.",
	Text71: "To allow remote users to join this local session you should provide your computer host name.",
	Text72: "Please enter the host name or IP address:",
	Text73: "To allow remote users to join this local session you should provide your computer host name.",
	Text74: "Please enter the host name or IP address:",
	Text75: "Can't connect: No fly file loaded",
	Text76: "Local Host",
	Text77: "Choose session name",
	Text78: "Start Session",
	Text79: "Session Name",
	Text80: "Connect",
	Text81: "Stop Session",
	Text82: "Disconnect",   
	Text83: "Please enter user name",
	Text84: "Broadcast location",
	Text85: "FreeHand",
	Text86: "Labels",
	Text87: "Chat",
	Text88: "Subject=Invitation to TerraExplorer Collaboration",
	Text93: "You have been invited to a collaboration session by ",
	Text96: "1. Open TerraExplorer (TerraExplorer with the Collaboration Extension must be installed first)",
	Text97: "2. From the Tools Menu select Collaboration",
	Text98: "3. Enter the following parameters in the Collaboration container:",
	Text99: "Server host name: " ,
	Text100: "Session name: " ,
	Text101: "4. Choose a user name",
	Text102: "5. Click the connect button",
	Text103: "Join<br/>Session",
	Text104: "Start<br/>Session",
	Text105: "My Color",
	Text106: "Label",
	Text107: "Add text label",
	Text108: "Draw",
	Text109: "Free hand drawing",
	Text110: "Cursor",
	Text111: "Virtual cursor",
	Text112: "Share",
	Text113: "Share my group",
	Text114: "Invite",
	Text115: "Invite a friend",
	Text116: "[Leader]",
	Text117: "[Manager]",
	Text118: "Collaboration",
	Text119: "I shared my folder",
	Text121: "Yes",
	Text122: "No",
	Text123: "Do not ask me again",
	Text124: "You are going to share folder <b>${folderName}</b> with all participants. Are you sure?",
	Text125: "Last shared:",
	Text126: "Never",
	Text127: "Share now",
	Text128: "[Auto sharing off]",
	Text129: "Session <b>${session}</b> on <b>${server}</b>",
	Text130: "A client request for current FLY file failed.\r\nReason: Can't transfer MPT file\r\nResolution: Please load a FLY file.",
	Text131: "[Auto sharing on]",
	Text132: "[My share group]",
	Text133: "Error receiving sharing group from ${name}:",
	Text134: "VirtualCursor",
	Text135: "Cursor",
	Text136: "Cursor1",
	Text137: "Cursor2",
	Text138: "Failed to load ${path}. Manually open a FLY file or terrain database to join the session.",
	Text139: "Failed to share file: ${path}\r\n${error}",
    SessionExists: "Session already exists. Access denied",
	notused: ""
});