SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "3D Viewshed On Route",
    help: "Help",
    Text4: "Model Type",
    Text5: "Car",
    Text6: "Humvee",
    Text7: "Tank",
    Text8: "Icon",
    Text9: "Empty",
    Text10: "Speed",
    Text11: "Km/h",
    Text12: "mph",
    Text13: "Loop",
    Text14: "No",
    Text15: "Yes",
    Text16: "Viewshed Distance",
    Text17: "m",
    Text18: "Clipboard ", //"Horizontal FOV",
    Text19: "deg.",
    Text20: "Vertical FOV",
    Text21: "Dynamic Object",
    Text22: "3D Viewshed",
    Text23: "Color Scheme",
    Text24: "Normal (Red/Green)",
    Text25: "Visible (Green)",
    Text26: "Not Visible (Red)",
    Text27: "Random",
    Text31: "Creating 3DViewshed #",
    Text32: "Follow<br> Line",
    Text33: "Selected<br> Group",
    Text34: "From<br>Clipboard",
    Text46: "Click on the terrain to place waypoints. Right click or click Finish button to generate the dynamic viewshed.",
    Text38: "Viewshed<br> Area",
    Text37: "Line",
    Text41: "N/A",
    Text42: "Distance",
    Text43: "meters",
    Text44: "Please select a group or a layer from the project tree",
    Text49: "Creating dynamic 3D viewshed...",
    Text50: "Unexpected error in 3D Dynamic Viewshed tool",
    Text51: "Dynamic 3D Viewshed tool is about to create more than 20 viewshed objects. This process may cause a system overload. Do you wish to continue?",
    Text52: "Spherical Viewshed",
    Text53: "Use Clipboard",
    Text54: "Start Time",
    Text55: "End Time",
    Text56: "Viewshed Interval",
    Text57: "Invalid Start Time",
    Text58: "Invalid End Time",
    Text59: "Viewer Height",
    Text60: "Calculating query points...",
    Text61: "Cannot generate viewshed query.",
    Text62: "Min Altitude",
    Text63: "Max Altitude",
    Text64: "Analyzing viewshed: ",
    Text65: "Analyzing points",
    Text66: "Viewshed",
    Text67: "Visible",
    Text68: "IconColor",
    Text69: "Spacing",
    Text70: "Dynamic 3D Viewshed tool is about to create more than ",
    Text71: " points. This process may take some time. Do you wish to continue?",
    Text72: "Calculating query points...",
    Text73: "Analyzing viewshed: ",
    Text74: "Analyzing point ",
    Text75: "Cannot perform query for multiple polyline objects",
    Text76: "Clipboard is empty",
    Text77: "ViewshedQuery",
    Text78: "This tool can be use on version 6.6 and above only",
    Text79: "Indicators",
    Text80: "Quality",
    Text81: "High",
    Text82: "Medium",
    Text83: "Low",
    

   
    

    Text999: ""
});