SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Create Pipe Lines",
    ToolName1: "Create Pipe Lines",
    help: "Help",
    Text1: "Pipe Radius",
    Text2: "meters",
    Text3: "Pipes",
    Text4: "Pipe",
    Text5: "Follow<br> Line",
    Text6: "Selected<br> Group",
    Text7: "Create pipe lines: Left clicks on the terrain to set the pipe line. Right click to finish operation",
    Text8: "Creating Objects ...",
    Text9: "connector",
    Text10: "Pipe Color",
    Text11:  "Gray" ,
    Text12:  "Yellow",
    Text13:  "Green" ,
    Text14:  "Blue" ,
    Text15:  "Purple",
    Text16: "Red",
    Text21: "Polyline",
    Text22: "Creating pipeline ",
    Text23: "Visibility Distance",
    Text24: "Connectors",
    Text69: "Please select a Group or a Layer from the project tree",
    Text70: "Create as",
    Text71: "Group",
    Text72: "Layer (Entire)",
    Text73: "Layer (Streaming)",
    ERROR_TEXT_NumPointsPassedQuota: "One or more of the objects you are creating has more than 10000 points, requiring a lengthy processing time. Click OK to continue or Cancel to abort.",
	VisibilityDistanceInvalid: "Visibility distance is invalid",
	RadiusInvalid: "Radius is invalid",
    Text74: "From<br>Clipboard",
    end: ""
});