SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Timespan Tags",
    PopupName: "Timespan Tags",
    help: "Help",
    Text1: "Start Time",
    Text2: "End Time",
    Text3 :"Set Time Stam",
    Text4: "Get Time Span",
    Text5: "Apply to<br> Group",
    Text6: "Please set the Start and End dates." ,
    Text7: "Setting time Spans",
    Text8: "Clear All<br>Group",
    Text9: "Number of objects ",
    Text10: "Show result",
    Text11: "Subgroup Objects",
    Text12: "Consecutive",
    Text13: "Simultaneous",
    Text14: "Time Span - Results",
    Text15: "Method",
    Text16: "Time Sequence",
    Text17: "Full Time Range",
    Text18: "Set Group",
    Text19: "Timespan tool only work with IE9 and above",
    Text20: "Make sure the End Time is larger than the Start Time",
    Text21: "Clear Group",
    Text22: "Are you sure you want to clear all timespan tags?",
    Text23: "Back to<br>timeline",
    Text24: "Could not find objects with timespan tags",
    Text25: "Please note: some objects in the group have no timespan tags",
    Text26: "Apply to",
    Text27: "All",
    Text28: "Objects without time",
    Text29: "Set timespan tags for group",
    Text30: "sec per loop",
    Text69: "Please select a group from the project tree and reactivate the tool.",
    Text70: "Name",
    Text71: "Duration",
    Text72: "Please select a group contains objects with time tags",
    Text73: "Unexpected error while trying to change objects date",


    end: ""
});