SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Terrain Profile",
    help: "Help",
    Text0: "Mode",
    Text1: "Normal",
    Text2: "Compare",
    Text3: "Calculating profile",
    Text5: "Elevation Layer",
    Text8: "Spacing",
    Text9: "meters",
    Text10: "Quality",
    Text11: "Medium",
    Text12: "High",
    Text13: "TerrainProfile",
    Text14: "TerrainProfile",
    Text15: "line ",
    Text16: "Left click on the terrain to draw a polygon/Polyline. Right click to finish operation.",
    Text18: "Follow <br>Line",
    Text19: "Calculating query points",
    Text20: "Terrain Profile tool cannot create more than 10 profiles. Operation aborted.",
    Text21: " objects. This procedure may take considerable time. Do you want to continue?",
    Text24: "Please select a group or a layer from the project tree",
    Text25: "Error while calculating elevation values.",
    Text26: "Please select an elevation layer from the list",
    Text27: "Point",
    Text28: "TerrainProfile-FollowLine",
    Text29: "Could not find lines in the clipboard.",
    Text31: "Analyzing point ",
    Text32: "Visibility Distance",
    Text33: "Follow<br>Line",
    Text34: "Fill <br>Area",
    Text35: "Selected<br>Group",
    Text36: "From<br>Clipboard",
    Text37: "<u>Refesh list</u>",
    Text40: "<b>Export to Layer</b>",
    Text43: "Distance",
    Text44: "Line",
    Text45: "Elevation",
    Text46: "Color",
    Text47: "Slope",
    Text48: "Min / Max Elevation",
    Text49: "Min / Max Slope",
    Text50: "Waypoint",
    Text51: "Unit:",
    Text52: "<b>meters</b>",
    Text53: "<b>feet</b>",


    Text999: ""
});