SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName:   "Indoor Views",
    help:       "Help",
    Text1: "Step 1: Select building",
    Text2:      "To start adding indoor views to a specific building click on the",
    Text3:      "Select Building",
    Text4:      "button and left click on the building you wish to select.",
    Text5:      "Step 2: Add indoor locations",
    Text6:      "Fly to a position inside the building. Type a <b>Location Name</b> for this camera position and click the <b>Add</b> button.",
    Text7:      "Location's Name:",
    Text8:      "Add",
    Text9:      "Indoor locations:",
    Text10:     "Finish",
    Text11:     "Clean All",
    Text12:     "Indoor views were assigned to the selected building.",
    Text13:     "To activate the Indoor navigation mode click on the <b>Enter </b>",
    Text14:     "icon above the building.",
    Text15:     "<b>Note:</b> You may change the Enter icons image and location. Make sure to keep the <b>Indoor</b> group name in the Information Tree.",
    Text16:     "Continue",
    Text17:     "Left click on the building model. Right click to cancel the operation",
	Text18:     "Please select a 3D Model object. Building objects are not supported",
	Text19:     "Unexpected error. Please try again",
	Text20:     "Please enter the location name",
	Text22: "No locations were assigned to the selected building.",
	Text23: "Cannot move selected building to indoor group. Building may be part of a streaming layer.",
	Text24: "Indoor",
	Indoor: "indoor.html"
});