SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Target",
    help: "Help",
    Text1: "Target location",
    Text2: "Numeric Entry",
    Text3: "Manual selection",
    Text4: "Target Mark Type",
    Text5: "No",
    Text6: "Arrow",
    Text7: "Circle",
    Text8: "Sphere",
    Text9: "Target scale",
    Text10: "Display Units",
    Text11: "Meter",
    Text12: "Feet",
    Text13: "Show Direction Arrow",
    Text14: "Yes",
    Text15: "Show MGRS",
    Text16: "X:",
    Text17: "Y: ",
    Text18: "H: ",
    Text19: "Camera Location:",
    Text20: "Cursor Location:",
    Text21: "Target Location: ",
    Text22: "Distance From Target:",
    Text23: "Set Target",
    Text24: "Reset",
    Text25: " Km",
    Text26: "miles",
    Text27: "Unknown terrain coordinate system.",
    Text28: "TerraExplorer",
    Text29: "Finish",
    Text30: "Left click on Terrain or Object to place target. Right click or Finish button to cancel operation. Reset button to clean results.",
    Text31: "NavToolDirArrow",
    Text32: "Mark",
    Text33: " X: ",
    Text34: " Y: ",
    Text35: " H: ",
    Text36: " AMSL",
    Text37: " MGRS",
    Text38: " Unknown",
    Text39: " Distance: ",
    Text40: " Distance: Unknown",
    Text41: " Lat/Long",
    Text42: "Fly To",

    Text99: ""
});