SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Multiple Coordinate Systems",
    ToolName1: "Multi-Coordinates",
    help: "Help",
    Text1: "Not Assigned",
    Text2: "Choose CS",
    Text3: "Latitude display mode:",
    Text4: "Decimal Degrees",
    Text5: "Degrees, Decimal Minutes",
    Text6: "Degrees, Minutes, Seconds",
    Text7: "<b>Camera Location:</b>",
    Text8: "<b>Cursor Location:</b>",
    Text9: "   View  ",
    Text10: "Invalid MGRS coordinate.",
    Text11: "Error.  Check preferences: distance setting for look at",
    Text12: "Error.  Check coordinates and preference settings.",
    Text13: "Choose coordinate system",
    Text14: " Latitude: ",
    Text15: " Longitude: ",
    Text16: " H: ",
    Text17: " feet AMSL",
    Text18: " meters AMSL",
    Text19: " Unknown",
    Text20: " X: ",
    Text21: " Y: ",
    Text22: "Invalid LAT-LONG coordinate.",
    Text23: "Invalid coordinate."
});