SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Image Comparison",
    ToolName1: "Image Comparison",
    help: "Help",
    Text1: "Swipe &<br> Fade",
    Text2: "Zoom to an area with an imagery layer <b>OR</b> select an imagery layer from the Project Tree and click:",
    Text3: "Unexpected Error: ",
    Text4: "Swipe<br>& Fade",
    Text5: "Could not detect an imagery layer in the view. Please zoom in to an area with a visible imagery layer and try again",
    Text6: "Snapshot Comparison",
    Text7: "Snapshot Comparison tool",
    Text12: "You must capture scenarios A and B before starting comparison operation",
    Text13: "Error while trying to load snapshot file",
    Text14: "Compare",
    Text15: "Image Comparison",
    Text16: "Imagery Layer Comparison",
    Text17: "Top Layer: ",
    Text20: "Error while trying to locate imagery layer. ",
    Text21: "Transparency",
    Text22: "Mode",
    Text23: "right-left",
    Text24: "left-right",
    Text25: "top-bottom",
    Text26: "bottom-top",
    Text27: "Auto",
    Text29: "Could not detect an imagery layer. Please zoom to an area with a visible imagery layer ",
    Text30: "Dynamic Comparison",
    Text31: "Loading Comparison",
    Text32: "Generating a high quality snapshot. This process may take a few seconds.",
    Text33: "Create a modified scene by showing or hiding objects in the Project Tree, and then click <b>Compare</b>",


    Text99: "Finish"
});