SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Data Library",
    ToolNameLayers: "Layers Library",
    ToolNameWarehouse: "SketchUp Warehouse",
    help: "Help",
    Text1: "<b>Urban Planning</b>:",
    Text2: "Traffic",
    Text3: "<b>Ground Vehicles</b>:",
    Text4: "<b>Air Planes</b>:",
    Text5: "<b>Helicopters</b>:",
    Text6: "Left click on the terrain to to add the selected 3D Model. Right click finish operation.",
    Text7: "Left click on the terrain to to add the selected icon. Right click finish operation.",
    Text8: "Left click on the terrain to to add the selected tree. Right click finish operation.",
    Text9: "Left click on the terrain to to add a building with the selected side texture. Right click finish operation.",
    Text10: "Left click on the terrain to to add a building with the selected roof texture. Right click finish operation.",
    Text11: "Left click on the terrain to to add a text label with the selected frame. Right click finish operation.",
    Text12: "Layers",
    Text13: "Icons",
    Text14: "Models",
    Text15: "Building Texture",
    Text16: "Online Models",
    Text17: "<b>Note:</b> This page works only on Globe projects.<br /><br />",
    Text18: "<b><u>World Layers:</b></u>",
    Text19: "<b><u>US Layers:</b></u>",
    Text20: "Countries",
    Text21: "World Capitals",
    Text22: "Major Cities",
    Text23: "Lat-Long Grid",
    Text24: "US States",
    Text25: "US Highways",
    Text26: "US Railroads",
    Text27: "US Airports",
    Text28: "<b>Map Signs</b>:",
    Text29: "<b>Trees</b>:",
    Text29a: "* Trees will apear in their original size",
    Text30: "<b>Letters and Numbers</b>:",
    Text31: "<b>Military Signs</b>:",
    Text32: "<b>Flags</b>:",
    Text33: "<b>Side Textures</b>:",
    Text34: "<b>Roof Textures</b>:",
    Text35: "<b>3D Models</b>:",
    Text36: "Search",
    Text37: "Enter 3D model name or category",
    Text38: "Instructions for loading a 3D model from ",
    Text39: "3D Warehouse:",
    Text40: "Enter the model to search for and click <b>Search</b>. The Sketchup 3D Warehouse opens displaying a collection of relevant thumbnail images.",
    Text41: "Click the thumbnail image of the model you want to download, click <b>Download</b>, and then from the drop-down list of formats, select either: <b>KMZ from SketchUp</b> or <b>Collada File (.zip)</b>.",
    Text42: "Save the model to your local or network drive.",
	Text43: "If you downloaded a model in KMZ format, load the model into your project by using TerraExplorer’s <b>Load KML/KMZ</b> command.",
    Text44: "If you downloaded a <b>Collada (DAE)</b> model, open the .zip file, and extract its contents to a folder. Then load the .dae file into your project by using TerraExplorer’s <b>Load 3D Model</b> command. ",
	Text45: "Online models require an Internet connection."
	
});