SGLang.lang = $.extend(SGLang.lang,{
    ToolName: "API Interactive Tutorial",
    Description: "Click on each line to see the effect of the action, and click on the <img src='images/source.gif' align=absmiddle /> to view the source code behind it.",
	ControlingCamera:"Controling the camera",
	ViewSource: "view <br /> source",
	ZoomIn:"Zoom in",
	ZoomOut:"Zoom out",
	ZoomToStreet:"Zoom to street level",
	GetCameraPoistion:"Get the camera position",
	SetCameraPoistion:"Set the camera position",
	JumpToPOI:"Jump to a distance from POI",
	ThickPolyline:"Draw thick polyline on terrain",
	ThinPolyline:"Draw thin polyline in the air",
	Polygons:"Drawing polygons",
	FilledCircle:"Draw filled circle",
	BasicLabels:"Draw basic text labels",
	LabelsWithImages:"Draw labels with images",
	Create3DModel:"Create 3D model",
	WorkingWithPopup:"Working with popups",
	SimplePopup:"Simple popup",
	PopupSizeAndPosition:"Popup size and position",
	TextPopup:"Simple text popup",
	TimedOutPopup:"Timed out popup without caption",
	MaximizedPopup:"Maximized popup",
	PopupSizeAndPosition2:"Popup size and position (2)",
	PopupRemoval:"Popup removal",
	Events:"Working with events",
	OnFrameEventMoveCamera:"onFrame - Moving the camera",
	OnFrameEventMoveObject:"onFrame - Moving objects",
	OnLButtonEvent:"onLButtonDown event",
	PreventingRightPopup:"Disable TE right context menu",
	OnMessageEvent:"onTerraExplorerMessage Event",
	Coordinates:"Working with coordinates",
	DistancesAndAngles:"Distances and angles",
	PositioningAndAiming:"Positioning and aiming",
	MovingToPosition:"Moving toward specific position",
	MovingTOPositionAndAimingToAnother:"Moving in one dir while aiming to another",
	AllTogether:"Putting it all together",
	Colors:"Working with colors",
	ColorSample:"Color sample",
	ObjectHierarchy:"Managing objects hierarchy",
	GroupingObjects:"Grouping objects",
	ObjectData:"Object data",
	TraversingObjects:"Traversing objects",
	SearchingNodes:"Searching nodes",
	RemovingNodes:"Removing nodes",
	Window3D:"Interacting with the 3D window",
	PixelToWorld:"Pixel to world",
	Layers:"Working with layers",
	ImageryLayer:"Imagery layers",
	FlyLayer:"Fly layers",
	SavingLoading:"Saving & loading",
	Saving:"Saving",
	Loading:"Loading",
	CodeSample:"code sample",
	CopyTip: "To copy this source code click on the <a id='selectCode'>Select Code</a> and then copy (Ctrl+C).",
	LoadingSampleError: "Error loading sample: ${error}",
	TE6: "TerraExplorer 6.0",
	TE61: "TerraExplorer 6.1",
	TE65: "TerraExplorer 6.5",
	SelectTEVersion: "Samples for: ",
	OnlyGlobeError: "Samples can only be executed in Globe projects. Click on the View Source icon to view the samples' source code.",
	"":""
});