SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Viewshed Query",
    help: "Help",
    Text0: "Create as",
    Text1: "Group",
    Text2: "Layer (Entire)",
    Text3: "Layer (Streaming)",
    Text4: "Measure every",
    Text5: "Query",
    Text6: "Out of Range",
    Text7: "Ignore Point",
    Text8: "Add Point",
    Text9: "Spacing",
    Text10: "meters",
    Text11: "Min Altitude",
    Text12: "Max Altitude",
    Text13: "ViewshedQuery",
    Text14: "Color Scheme",
    Text15: "red | green",
    Text16: "red | orange | yellow | green",
    Text17: "Left click on the terrain to draw polygon. Right click or Finish button to finish operation.",
    Text18: "Follow <br>Line",
    Text19: "Calculating query points",
    Text20: "Viewshed Query tool is about to create ",
    Text21: " query points. This procedure may take some time. Do you wish to continue?",
    Text22: "Analyzing viewshed: ",
    Text24: "Please select a group or a layer from the project tree",
    Text26: "Cannot generate viewshed query.",
    Text27: "Point",
    Text28: "Viewshed Query tool cannot detect a 3D Viewshed object in the project.",
    Text29: "Could not detect any point in the region of the selected 3D Viewshed. Please make sure to select the correct 3D Viewshed from the list.",
    Text30: "Please select one or more 3D Viewsheds from the query list",
    Text31: "Analyzing point ",
    Text32: "Visibility Distance",
    Text33: "Follow<br>Line",
    Text34: "Fill <br>Area",
    Text35: "Selected<br>Group",
    Text36: "From<br>Clipboard",
    Text37: "refresh list",
    Text38: "Viewshed<br> Area",
    Text39: "Viewsheds",
    Text40: "Visible",
    Text41: "IconColor",
    Text42: "select in view",
    Text43: "Altitude Mode",
    Text44: "Follow Terrain & Objects",
    Text45: "Follow Terrain",




    Text999: ""
});