SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Shadow Query",
    help: "Help",
    Text0: "Create as",
    Text1: "Group",
    Text2: "Layer (Entire)",
    Text3: "Layer (Streaming)",
    Text4: "Measure every",
    Text5: "Query",
    Text6: "minutes",
    Text8: "Spacing",
    Text9: "meters",
    Text10: "Min Altitude",
    Text11: "Max Altitude",
    Text13: "ShadowQuery",
    Text14: "Start Time",
    Text15: "End Time",
    Text16: "Left click on the terrain to draw a polygon/Polyline. Right click to finish operation.",
    Text17: "Hr.",
    Text18: "Follow <br>Line",
    Text19: "Calculating query points",
    Text20: "Shadow Query tool is about to create more than ",
    Text21: " objects. This procedure may take considerable time. Do you want to continue?",
    Text22: "Analyzing time: ",
    Text23: "Invalid input: Start Time must be earlier than or same as the End Time",
    Text24: "Please select a group or a layer from the project tree",
    Text25: "Time Zone",
    Text27: "Point",
    Text28: "The difference between the calculated time zone and the selected one is too large. Do you want to continue?",
    Text31: "Analyzing point ",
    Text32: "Visibility Distance",
    Text33: "Follow<br>Line",
    Text34: "Fill <br>Area",
    Text35: "Selected<br>Group",
    Text36: "From<br>Clipboard",
    Text37: "Global Shadow",
    Text38: "Selection Shadow",
    Text39: "Selection Shadow supplement",
    Text40: "Cannot generate shadow query. Please make sure the global shadow is visible",
    Text41: "Cannot generate shadow query. Please make sure the selection shadow is visible",
    Text42: "Cannot generate shadow query. Please make sure the global and selection shadow are visible",
    Text43: "StartDate",
    Text44: "EndDate",
    Text45: "AddedShdw",
    Text46: "AvrShadow",
    Text47: "Cannot generate shadow query. The length of the query region is greater than 1500 meters. Please reduce the size of your query region.",


    Text6AM: "6 AM",
    Text7AM: "7 AM",
    Text8AM: "8 AM",
    Text9AM: "9 AM",
    Text10AM: "10 AM",
    Text11AM: "11 AM",
    Text12AM: "12 AM",
    Text1PM: "1 PM",
    Text2PM: "2 PM",
    Text3PM: "3 PM",
    Text4PM: "4 PM",
    Text5PM: "5 PM",
    Text6PM: "6 PM",
    Text7PM: "7 PM",
    Text8PM: "8 PM",

    Text999: ""
});