SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe Pro - Skyline Software Systems, Inc.",
    ToolName: "GPS Tracking",
    help: "Help",
    Text1: "Read stream from:",
    Text2: "File",
    Text3: "Bits per second:",
    Text4: "Data bits:",
    Text5: "Parity:",
    Text6: "Even",
    Text7: "Odd",
    Text8: "None",
    Text9: "Mark",
    Text10: "Space",
    Text11: "Stop bits:",
    Text12: "Flow control:",
    Text13: "Xon / Xoff",
    Text14: "Hardware",
    Text15: "None",
    Text16: "Stream File:",
    Text17: "Stream from this IP Address:",
    Text18: "Stream from this Port:",
    Text19: "Format:",
    Text20: "Use private command: ",
    Text21: "Yes",
    Text22: "No",
    Text23: "Command Name: ",
    Text24: "Stream Rate: ",
	Text25: "Display Objects As:",
    Text26: "Text Label",
    Text27: "Image Label",
    Text28: "Regular Polygon",
    Text29: "Arrow",
    Text30: "Circle",
    Text31: "Ellipse",
    Text32: " 3D Model",
    Text33: " Box",
    Text34: " Cylinder",
    Text35: " Sphere",
    Text36: " Cone",
    Text37: " Pyramid",
    Text38: " 3D Arrow",
    Text39: "Scale: ",
    Text40: "Text:",
    Text41: "text",
    Text42: "Color: ",
    Text43: "Draw Trace Line: ",
    Text44: "Trace Length (points): ",
    Text45: "Save Option: ",
    Text46: "Delete At Disconnect",
    Text47: "Keep Alive While in Project",
    Text48: "Save in FLY Project",
	Text49: "Connect",
	Text50: ". Please run Start>Programs>Skyline>License Manager for additional information",
    Text51: "Disconnected from GPS communication port...",
    Text52: "You must select a file before connecting.",
    Text53: "Connect to GPS communication port...",
	Text54: "Text",
    Text55: "Scale:",
    Text56: "File Name",
    Text57: "Num. of Segments:",
    Text58: "meters",
	Text59: "N/A",
	Text60: "Length:",
    Text61: "Radius:",
    Text62: "Second Radius",
    Text63: "Box Height",
	Text64: "Base Size:",
    Text65: "Cylinder Height",
    Text66: "Base Size:",
    Text67: "Cone Height",
    Text68: "Pyramid Height",
	Text69: "Arrow Height",
	Text70: "Base Length:",
	Text71: "Connect",
	Text72: "Disconnect",
    Text73: "You must select a model file name before connecting"
});