SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Slope Map Query",
    help: "Help",
    Text0: "Create as",
    Text1: "Group",
    Text2: "Layer (Entire)",
    Text3: "Layer (Streaming)",
    Text8: "Spacing",
    Text9: "meters",
    Text13: "SlopeMapQuery",
    Text16: "Left click on the terrain to draw a polygon/Polyline. Right click to finish operation.",
    Text18: "Follow <br>Line",
    Text19: "Calculating query point",
    Text20: "Slope Map Query tool is about to create more than ",
    Text21: " objects. This procedure may take considerable time. Do you want to continue?",
    Text24: "Please select a group or a layer from the project tree",
    Text25: "Error while calculating slope values.",
    Text26: "Calculating slope point",
    Text27: "Point",
    Text31: "Analyzing point ",
    Text32: "Visibility Distance",
    Text33: "Follow<br>Line",
    Text34: "Fill <br>Area",
    Text35: "Selected<br>Group",
    Text36: "From<br>Clipboard",
    Text43: "SlopeValue",
    Text44: "SlopeDir",
    Text45: "Altitude",
    Text46: "IconColor",


    Text999: ""
});