SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Indoor Navigation",
    ToolName1: "Indoor Navigation Mode",
    help: "Help",
    Text1: "Please click on the building entry location or click",
    Text2: "<u>here</u>",
    Text3: "to start the indoor navigation",
    Text4: "Start",
    Text5: "Stop",
    Text7: "Are you sure you want to delete this location?",
    Text8: "Yes",
    Text9: "No",
    Text10: "Name:",
    Text11: "OK",
    Text12: "Cancel",
    Text13: "New name:",
    Text14: "Error in location list page.",
    AddBuilding: "Add Building",
    AddLocation: "Add Location",
    CollisionAlt: "Collision Detection on/off",
    CollisionTxt: "Collision",
    FovAlt: "Camera field of view",
    FOVTxt: "FOV",
    UpAlt: "Move up to the next floor",
    DownAlt: "Move down to the next floor",
    ForwardAlt: "Move down to the next room ",
    BackAlt: "Move down to the room behind",
    LeftAlt: "Move down to the room on the right",
    RightAlt: "Move down to the room on the left",
    XRayAlt: "XRay mode on/off",
    XRayTxt: "X-Ray",
    NavigationAlt: "Next Room",
    LocationAlt: "Show and add locations",
    Locations: "Indoor Locations",
    Buildings: "Buildings",
    LocationsGroup: "$$Indoor_Locations",
    ExitAlt: "Exit",


    Text99: "Finish"
});